### ISSUE TITLE
Error PHP

### ISSUE THREAD

**Issue by TeamForest** [sant0ro/habbo-asset-extractor#1]
[19-Nov-2015 18:53:38 Europe/Berlin] PHP Notice:  Undefined offset: 1 in C:\camera\assets\assets.php on line 285

**Comment by TeamForest** [comment]
When you reach a file number is stop

**Comment by sant0ro** [comment]
Which PhP version?

**Comment by TeamForest** [comment]
5.6

**Comment by sant0ro** [comment]
I really don't know that can be that.

Probably reasons:
1. PhP cut the script execution because time_limit (not probably)
2. Your internet cut connection cuts in some time that makes one of the procedures doesnt work.
3. This is a notice not an error, but please give me a screen of that error.
4. An user of RZ said not all assets can be extracted with the Asset Extractor, because some assets has different way of naming.

Cheers,
