### ISSUE TITLE
Error:

### ISSUE THREAD

**Issue by xJuice** [sant0ro/habbo-asset-extractor#5]
Habbo SWF Furniture resource dump Tool
OFFICIAL RESOURCE URL : http://www.habbo.com
FLASH CLIENT URL      : http://habboo-a.akamaihd.net/gordon/PRODUCTION-201512170847-152005991/
OUTPUT PATH           : D:\inetpub\wwwroot\habbo-asset-extractor-master/download/
DCR URL               : http://habboo-a.akamaihd.net/dcr/hof_furni/
Extract FurniData
Download: http://www.habbo.com/gamedata/furnidata_xml/1a82719e4dc9913d3b605547098b5211d3319e36
Connected...
Mime-type: text/html
Filesize: 6597
Error: file_get_contents(http://www.habbo.com/gamedata/furnidata_xml/1a82719e4dc9913d3b605547098b5211d3319e36): failed to open stream: HTTP request failed! HTTP/1.1 463 
Notice: Trying to get property of non-object in D:\inetpub\wwwroot\habbo-asset-extractor-master\assets.php on line 210 Warning: Invalid argument supplied for foreach() in D:\inetpub\wwwroot\habbo-asset-extractor-master\assets.php on line 210 Notice: Trying to get property of non-object in D:\inetpub\wwwroot\habbo-asset-extractor-master\assets.php on line 220 Warning: Invalid argument supplied for foreach() in D:\inetpub\wwwroot\habbo-asset-extractor-master\assets.php on line 220
Starting RoomTypes
Starting WallTypes
update complete.

Why you dont give me the Downloadlink for the Folders?

**Comment by sant0ro** [comment]
Oh god. Your PhP configuration, blocks remote requests.

**Comment by xJuice** [comment]
No,  masks.php works.

i downloaded php 5.5 and i enable all extensions .

why you fuck me up ?

**Comment by sant0ro** [comment]
Sorry, why are you saying that?
Is not my problem if you doesn't know use basics of PhP.

This is a Develoipment Software. Not a software for noobs, where you download click two times and open.

Github issues isn't for these type of Questions. Github is a Development Place. The usage questions must be minimal compreensive.

You must analyse your own errors, and not going cry to the developer of the software and saying that the software has errors.

A lot of people used successfully this software.

I know that exists possibility of usage issues. But IS USAGE ISSUES. The instructions of this software are specific.

1. Download
2. Download C++ 2015 Redistributable
3. PhP 5.5x+
4. Put Valid Habbo Urls
5. Check if your PhP configuration and Apache Configuration allow remote connection (likely curl, or remote string download)
6. And you need rune the PhP scripts in Browser.
7. Remember you need use WINDOWS for that. Because the Script has some .exes
8. Please don't put this script in a webhost. Use in localhost.
9. Please check if your PhP configuration allow this execution.

The HTTP 463 Error isn't a ERROR from THE SCRIPT.

IF YOU MINIMALLY READ THE ERROR, AND SEARCH IN INTERNET, WILL KNOW THAT THIS IS NOT A FUCKIN ERROR FROM THIS SCRIPT. BUT YOUR.

Usage issues, is in error for scripts, or for know the best usage of arguments for the script. But this script has not arguments.

Issue closed. If you do the same question again. I will no answer. Bye.

**Comment by sant0ro** [comment]
Okay ;)

**Comment by xJuice** [comment]
you are the worst developer what i see .

i dont use your products  anymore.

go kill yourself bb

**Comment by sant0ro** [comment]
Huh?
